export interface Character {
  disabled: boolean;
  id: string;
  image: string;
  key: string;
  name: string;
  selected: boolean;
}

export const DEFAULT_CHARACTER: Character = {
  disabled: false,
  id: 'default',
  image: 'placeholder.png',
  key: 'default',
  name: 'DEFAULT',
  selected: false,
};

export const CHARACTER_LIST: Character[] = [
  {
    disabled: false,
    id: 'mario',
    image: 'mario.png',
    key: 'mario',
    name: 'MARIO',
    selected: false,
  },
  {
    disabled: false,
    id: 'donkey-kong',
    image: 'donkey-kong.png',
    key: 'donkey-kong',
    name: 'DONKEY KONG',
    selected: false,
  },
  {
    disabled: false,
    id: 'link',
    image: 'link.png',
    key: 'link',
    name: 'LINK',
    selected: false,
  },
  {
    disabled: false,
    id: 'samus',
    image: 'samus.png',
    key: 'samus',
    name: 'SAMUS',
    selected: false,
  },
  {
    disabled: false,
    id: 'dark-samus',
    image: 'dark-samus.png',
    key: 'dark-samus',
    name: 'DARK SAMUS',
    selected: false,
  },
  {
    disabled: false,
    id: 'yoshi',
    image: 'yoshi.png',
    key: 'yoshi',
    name: 'YOSHI',
    selected: false,
  },
  {
    disabled: false,
    id: 'kirby',
    image: 'kirby.png',
    key: 'kirby',
    name: 'KIRBY',
    selected: false,
  },
  {
    disabled: false,
    id: 'fox',
    image: 'fox.png',
    key: 'fox',
    name: 'FOX',
    selected: false,
  },
  {
    disabled: false,
    id: 'pikachu',
    image: 'pikachu.png',
    key: 'pikachu',
    name: 'PIKACHU',
    selected: false,
  },
  {
    disabled: false,
    id: 'luigi',
    image: 'luigi.png',
    key: 'luigi',
    name: 'LUIGI',
    selected: false,
  },
  {
    disabled: false,
    id: 'ness',
    image: 'ness.png',
    key: 'ness',
    name: 'NESS',
    selected: false,
  },
  {
    disabled: false,
    id: 'captain-falcon',
    image: 'captain-falcon.png',
    key: 'captain-falcon',
    name: 'CAPTAIN FALCON',
    selected: false,
  },
  {
    disabled: false,
    id: 'jigglypuff',
    image: 'jigglypuff.png',
    key: 'jigglypuff',
    name: 'JIGGLYPUFF',
    selected: false,
  },
  {
    disabled: false,
    id: 'peach',
    image: 'peach.png',
    key: 'peach',
    name: 'PEACH',
    selected: false,
  },
  {
    disabled: false,
    id: 'daisy',
    image: 'daisy.png',
    key: 'daisy',
    name: 'DAISY',
    selected: false,
  },
  {
    disabled: false,
    id: 'bowser',
    image: 'bowser.png',
    key: 'bowser',
    name: 'BOWSER',
    selected: false,
  },
  {
    disabled: false,
    id: 'ice-climbers',
    image: 'ice-climbers.png',
    key: 'ice-climbers',
    name: 'ICE CLIMBERS',
    selected: false,
  },
  {
    disabled: false,
    id: 'sheik',
    image: 'sheik.png',
    key: 'sheik',
    name: 'SHEIK',
    selected: false,
  },
  {
    disabled: false,
    id: 'zelda',
    image: 'zelda.png',
    key: 'zelda',
    name: 'ZELDA',
    selected: false,
  },
  {
    disabled: false,
    id: 'dr-mario',
    image: 'dr-mario.png',
    key: 'dr-mario',
    name: 'DR. MARIO',
    selected: false,
  },
  {
    disabled: false,
    id: 'pichu',
    image: 'pichu.png',
    key: 'pichu',
    name: 'PICHU',
    selected: false,
  },
  {
    disabled: false,
    id: 'falco',
    image: 'falco.png',
    key: 'falco',
    name: 'FALCO',
    selected: false,
  },
  {
    disabled: false,
    id: 'marth',
    image: 'marth.png',
    key: 'marth',
    name: 'MARTH',
    selected: false,
  },
  {
    disabled: false,
    id: 'lucina',
    image: 'lucina.png',
    key: 'lucina',
    name: 'LUCINA',
    selected: false,
  },
  {
    disabled: false,
    id: 'young-link',
    image: 'young-link.png',
    key: 'young-link',
    name: 'YOUNG LINK',
    selected: false,
  },
  {
    disabled: false,
    id: 'ganondorf',
    image: 'ganondorf.png',
    key: 'ganondorf',
    name: 'GANONDORF',
    selected: false,
  },
  {
    disabled: false,
    id: 'mewtwo',
    image: 'mewtwo.png',
    key: 'mewtwo',
    name: 'MEWTWO',
    selected: false,
  },
  {
    disabled: false,
    id: 'roy',
    image: 'roy.png',
    key: 'roy',
    name: 'ROY',
    selected: false,
  },
  {
    disabled: false,
    id: 'chrom',
    image: 'chrom.png',
    key: 'chrom',
    name: 'CHROM',
    selected: false,
  },
  {
    disabled: false,
    id: 'mr-game-and-watch',
    image: 'mr-game-and-watch.png',
    key: 'mr-game-and-watch',
    name: 'MR. GAME AND WATCH',
    selected: false,
  },
  {
    disabled: false,
    id: 'meta-knight',
    image: 'meta-knight.png',
    key: 'meta-knight',
    name: 'META KNIGHT',
    selected: false,
  },
  {
    disabled: false,
    id: 'pit',
    image: 'pit.png',
    key: 'pit',
    name: 'PIT',
    selected: false,
  },
  {
    disabled: false,
    id: 'dark-pit',
    image: 'dark-pit.png',
    key: 'dark-pit',
    name: 'DARK PIT',
    selected: false,
  },
  {
    disabled: false,
    id: 'zero-suit-samus',
    image: 'zero-suit-samus.png',
    key: 'zero-suit-samus',
    name: 'ZERO SUIT SAMUS',
    selected: false,
  },
  {
    disabled: false,
    id: 'wario',
    image: 'wario.png',
    key: 'wario',
    name: 'WARIO',
    selected: false,
  },
  {
    disabled: false,
    id: 'snake',
    image: 'snake.png',
    key: 'snake',
    name: 'SNAKE',
    selected: false,
  },
  {
    disabled: false,
    id: 'ike',
    image: 'ike.png',
    key: 'ike',
    name: 'IKE',
    selected: false,
  },
  {
    disabled: false,
    id: 'pokemon-trainer',
    image: 'pokemon-trainer.png',
    key: 'pokemon-trainer',
    name: 'POKEMON TRAINER',
    selected: false,
  },
  {
    disabled: false,
    id: 'diddy-kong',
    image: 'diddy-kong.png',
    key: 'diddy-kong',
    name: 'DIDDY KONG',
    selected: false,
  },
  {
    disabled: false,
    id: 'lucas',
    image: 'lucas.png',
    key: 'lucas',
    name: 'LUCAS',
    selected: false,
  },
  {
    disabled: false,
    id: 'sonic',
    image: 'sonic.png',
    key: 'sonic',
    name: 'SONIC',
    selected: false,
  },
  {
    disabled: false,
    id: 'king-dedede',
    image: 'king-dedede.png',
    key: 'king-dedede',
    name: 'KING DEDEDE',
    selected: false,
  },
  {
    disabled: false,
    id: 'olimar',
    image: 'olimar.png',
    key: 'olimar',
    name: 'OLIMAR',
    selected: false,
  },
  {
    disabled: false,
    id: 'lucario',
    image: 'lucario.png',
    key: 'lucario',
    name: 'LUCARIO',
    selected: false,
  },
  {
    disabled: false,
    id: 'rob',
    image: 'rob.png',
    key: 'rob',
    name: 'R.O.B.',
    selected: false,
  },
  {
    disabled: false,
    id: 'toon-link',
    image: 'toon-link.png',
    key: 'toon-link',
    name: 'TOON LINK',
    selected: false,
  },
  {
    disabled: false,
    id: 'wolf',
    image: 'wolf.png',
    key: 'wolf',
    name: 'WOLF',
    selected: false,
  },
  {
    disabled: false,
    id: 'villager',
    image: 'villager.png',
    key: 'villager',
    name: 'VILLAGER',
    selected: false,
  },
  {
    disabled: false,
    id: 'megaman',
    image: 'megaman.png',
    key: 'megaman',
    name: 'MEGAMAN',
    selected: false,
  },
  {
    disabled: false,
    id: 'wii-fit-trainer',
    image: 'wii-fit-trainer.png',
    key: 'wii-fit-trainer',
    name: 'WII FIT TRAINER',
    selected: false,
  },
  {
    disabled: false,
    id: 'rosalina',
    image: 'rosalina.png',
    key: 'rosalina',
    name: 'ROSALINA & LUMA',
    selected: false,
  },
  {
    disabled: false,
    id: 'little-mac',
    image: 'little-mac.png',
    key: 'little-mac',
    name: 'LITTLE MAC',
    selected: false,
  },
  {
    disabled: false,
    id: 'greninja',
    image: 'greninja.png',
    key: 'greninja',
    name: 'GRENINJA',
    selected: false,
  },
  {
    disabled: false,
    id: 'palutena',
    image: 'palutena.png',
    key: 'palutena',
    name: 'PALUTENA',
    selected: false,
  },
  {
    disabled: false,
    id: 'pac-man',
    image: 'pac-man.png',
    key: 'pac-man',
    name: 'PAC-MAN',
    selected: false,
  },
  {
    disabled: false,
    id: 'robin',
    image: 'robin.png',
    key: 'robin',
    name: 'ROBIN',
    selected: false,
  },
  {
    disabled: false,
    id: 'shulk',
    image: 'shulk.png',
    key: 'shulk',
    name: 'SHULK',
    selected: false,
  },
  {
    disabled: false,
    id: 'bowser-jr',
    image: 'bowser-jr.png',
    key: 'bowser-jr',
    name: 'BOWSER JR.',
    selected: false,
  },
  {
    disabled: false,
    id: 'duck-hunt',
    image: 'duck-hunt.png',
    key: 'duck-hunt',
    name: 'DUCK HUNT',
    selected: false,
  },
  {
    disabled: false,
    id: 'ryu',
    image: 'ryu.png',
    key: 'ryu',
    name: 'RYU',
    selected: false,
  },
  {
    disabled: false,
    id: 'ken',
    image: 'ken.png',
    key: 'ken',
    name: 'KEN',
    selected: false,
  },
  {
    disabled: false,
    id: 'cloud',
    image: 'cloud.png',
    key: 'cloud',
    name: 'CLOUD',
    selected: false,
  },
  {
    disabled: false,
    id: 'corrin',
    image: 'corrin.png',
    key: 'corrin',
    name: 'CORRIN',
    selected: false,
  },
  {
    disabled: false,
    id: 'bayonetta',
    image: 'bayonetta.png',
    key: 'bayonetta',
    name: 'BAYONETTA',
    selected: false,
  },
  {
    disabled: false,
    id: 'inkling',
    image: 'inkling.png',
    key: 'inkling',
    name: 'INKLING',
    selected: false,
  },
  {
    disabled: false,
    id: 'ridley',
    image: 'ridley.png',
    key: 'ridley',
    name: 'RIDLEY',
    selected: false,
  },
  {
    disabled: false,
    id: 'simon',
    image: 'simon.png',
    key: 'simon',
    name: 'SIMON',
    selected: false,
  },
  {
    disabled: false,
    id: 'richter',
    image: 'richter.png',
    key: 'richter',
    name: 'RICHTER',
    selected: false,
  },
  {
    disabled: false,
    id: 'king-k-rool',
    image: 'king-k-rool.png',
    key: 'king-k-rool',
    name: 'KING K. ROOL',
    selected: false,
  },
  {
    disabled: false,
    id: 'isabelle',
    image: 'isabelle.png',
    key: 'isabelle',
    name: 'ISABELLE',
    selected: false,
  },
  {
    disabled: false,
    id: 'incineroar',
    image: 'incineroar.png',
    key: 'incineroar',
    name: 'INCINEROAR',
    selected: false,
  },
  {
    disabled: false,
    id: 'piranha-plant',
    image: 'piranha-plant.png',
    key: 'piranha-plant',
    name: 'PIRANHA PLANT',
    selected: false,
  },
  {
    disabled: false,
    id: 'joker',
    image: 'placeholder.png',
    key: 'joker',
    name: 'JOKER',
    selected: false,
  },
  {
    disabled: false,
    id: 'hero',
    image: 'placeholder.png',
    key: 'hero',
    name: 'HERO',
    selected: false,
  },
  {
    disabled: false,
    id: 'banjo-kazooie',
    image: 'placeholder.png',
    key: 'banjo-kazooie',
    name: 'BANJO & KAZOOIE',
    selected: false,
  },
  {
    disabled: false,
    id: 'terry',
    image: 'placeholder.png',
    key: 'terry',
    name: 'TERRY',
    selected: false,
  },
  {
    disabled: true,
    id: 'mii-brawler',
    image: 'mii-brawler.png',
    key: 'mii-brawler',
    name: 'MII BRAWLER',
    selected: false,
  },
  {
    disabled: true,
    id: 'mii-swordfighter',
    image: 'mii-swordfighter.png',
    key: 'mii-swordfighter',
    name: 'MII SWORDFIGHTER',
    selected: false,
  },
  {
    disabled: true,
    id: 'mii-gunner',
    image: 'mii-gunner.png',
    key: 'mii-gunner',
    name: 'MII GUNNER',
    selected: false,
  },
];
